
Vagrant.configure("2") do |ubuntu|
  ubuntu.vm.box = "bento/ubuntu-20.04-arm64"
  ubuntu.vm.network "public_network"
  ubuntu.vm.provider "vmware_desktop" do |vb|
    vb.gui = false 
    vb.memory = "1024"
    vb.cpus = 1
    
end