Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-23.04-arm64"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.10.11"
    ubuntu.vm.provider "vmware_desktop" do |vb|
      vb.gui = false 
      vb.memory = "1024"
      vb.cpus = 1
    end
    #Lembra de comentar a linha abaixo quando for subir pela primeira vez
    #ubuntu.vm.provision "shell", path: "/provision/provision_ubuntu.sh" 
  
  end


  config.vm.define "debian" do |debian|
    debian.vm.box = "bento/debian-12-arm64"
    debian.vm.hostname = "debian"
    debian.vm.network "private_network", ip: "192.168.10.10"
    debian.vm.provider "vmware_desktop" do |vb|
      vb.gui = false 
      vb.memory = "1024"
      vb.cpus = 1
    end
    #Lembra de comentar a linha abaixo quando for subir pela primeira vez
    #debian.vm.provision "shell", path: "provision/provision_debian.sh"
      
  end

end