
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04-arm64"
  config.vm.hostname = "ubuntu"
  config.vm.provider "vmware_desktop"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y vim curl telnet unzip wget net-tools htop nmap
    useradd matheus

   SHELL
end
