---
- name: Install Nginx and copy file html
  hosts: all
  become: true 
  tasks: 
    - name: Install Nginx
      apt: 
        name: nginx
        state: latest
    - name: start service nginx
      service:
        name: nginx
        state: started
    - name: copy file html
      ansible.builtin.copy:
        src: files/
        dest: /var/www/html/

