Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04-arm64"
  config.vm.hostname = "ubuntu"
  config.vm.provider "vmware_desktop"
  config.vm.network "public_network", ip: "192.168.1.8"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end 
end
