Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04-arm64"
    config.vm.hostname = "ubuntu"
    config.vm.provider "vmware_desktop"
    config.vm.network "public_network", ip: "192.168.1.7"
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx
      useradd matheus
  
     SHELL
    config.vm.synced_folder "files/", "/var/www/html/"

  end
  